baseURL: 'http://lindemann.co/'
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Lindemann
theme: hello-friend-ng
paginate: 100

enableRobotsTXT: true

author:
  name: Mathieu Lindemann

params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  enableThemeToggle: true
  enableSharingButtons: true
  homeSubtitle:  <a href="/en/about">English</a> &#x2022; <a href="/fr/a-propos">Français</a>
  footer:
    trademark: true
    rss: true
    copyright: false
    author: true
  logo:
    logoMark: $
    logoText: '~'
    logoHomeLink: /
    logoCursorDisabled: false
    logoCursorColor: '#555'
    logoCursorAnimate: 3s
    logoCursorPathname: false

taxonomies:
  category: blog
  tag: tags
  series: series

languages:
  fr:
    params:
      subtitle: Bienvenue
      keywords: ''
      copyright: >-
        <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
        rel="noopener">CC BY-NC 4.0</a>
      readOtherPosts: Voir les autres pages.
      footer:
        trademark: true
        rss: true
        copyright: false
        author: true
        bottomText:
          - 'Thème réalisé par <a href="https://github.com/rhazdon">DA</a>'
    menu:
      main:
        - name: À propos
          url: /a-propos
          weight: 20
        - name: Citations
          url: /citations/all
          weight: 40
        - name: EN
          url: ../en/about
          weight: 1000
  en:
    params:
      subtitle: Welcome
      keywords: ''
      copyright: >-
        <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
        rel="noopener">CC BY-NC 4.0</a>
      readOtherPosts: Read other posts
      footer:
        trademark: true
        rss: true
        copyright: false
        author: true
        bottomText:
          - 'Theme by <a href="https://github.com/rhazdon">DA</a>'
    menu:
      main:
        - name: About
          url: /about
          weight: 20
        - name: Quotes
          url: /quotes/all
          weight: 40
        - name: FR
          url: ../fr/a-propos
          weight: 1000
